version: '3'
services:
  db:
    image: rethinkdb:2.3.5
    ports:
      - 4000:8080

  discovery-service:
    build: ./discovery-service
    working_dir: /usr/app
    ports:
      - 4001:4000
    environment:
      - MOVIE_SERVICE_HOST=http://movie-service:4000
      - SHOW_SERVICE_HOST=http://show-service:4000
      - ORDER_SERVICE_HOST=http://order-service:4000

  movie-service:
    build: ./movie-service
    working_dir: /usr/app
    depends_on:
      - db
    ports:
      - 4002:4000
    environment:
      - DB_HOST=db
    command: ["npm", "run", "start:preloaded"]

  order-service:
    build: ./order-service
    working_dir: /usr/app
    depends_on:
      - db
    ports:
      - 4003:4000
    environment:
      - DB_HOST=db
      - SHOW_SERVICE_HOST=http://show-service:4000
      - MOVIE_SERVICE_HOST=http://movie-service:4000
    command: ["npm", "run", "start:preloaded"]

  show-service:
    build: ./show-service
    working_dir: /usr/app
    depends_on:
      - db
    ports:
      - 4004:4000
    environment:
      - DB_HOST=db
      - MOVIE_SERVICE_HOST=http://movie-service:4000
    command: ["npm", "run", "start:preloaded"]

  web-client:
    build: ./web-client
    ports:
      - 4005:4000
    depends_on:
      - discovery-service
